---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::jinja2=3.1.6
  - conda-forge::pandas=2.3.3
  - conda-forge::python=3.13.2
  - conda-forge::biopython=1.85
